In [1]:
import pandas as pd
import numpy as np

In [2]:
df_chicago = pd.read_csv("listings (2).csv")
df_new_orleans = pd.read_csv("listings (3).csv")

In [22]:
print(df_chicago.shape)
df_new_orleans.shape

(6099, 19)

(8663, 18)

In [5]:
df_chicago.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='str')

In [6]:
df_new_orleans.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='str')

In [12]:
def clean_data(df, city_name):
    
    # Handle missing values
    df['reviews_per_month'] = df['reviews_per_month'].fillna(0)
    df

In [13]:
# Fill missing values
df_chicago['reviews_per_month'] = df_chicago['reviews_per_month'].fillna(0)

In [14]:

# Drop important nulls
df_chicago = df_chicago.dropna(subset=['price', 'neighbourhood', 'room_type'])

In [24]:

# Clean price
df_chicago['price'] = df_chicago['price'].replace(r'[\$,]', '', regex=True)

In [16]:

# Convert date
df_chicago['last_review'] = pd.to_datetime(df_chicago['last_review'], errors='coerce')

In [17]:


# Remove duplicates
df_chicago = df_chicago.drop_duplicates()

In [18]:


# Fix text
df_chicago['neighbourhood'] = df_chicago['neighbourhood'].str.lower().str.strip()
df_chicago['room_type'] = df_chicago['room_type'].str.lower().str.strip()

In [19]:

# Remove outliers
df_chicago = df_chicago[df_chicago['price'] < 1000]
df_chicago = df_chicago[df_chicago['minimum_nights'] < 365]

In [20]:

# Add city column
df_chicago['city'] = 'Chicago'

In [21]:
df_chicago

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city
0,19091,Fully Furnished Cozy Apartment,72880,John,NaN,leonidas,29.96100,-90.11950,entire home/apt,61.0,1,510,2025-08-31,2.72,1,331,7,"25-NSTR-11772, 25-OSTR-11151",Chicago
1,71624,Ravenwood Manor (Historic Bywater),367223,Susan,NaN,bywater,29.96153,-90.04364,entire home/apt,150.0,30,316,2025-05-07,1.78,1,356,7,"21-RSTR-18609, 22-OSTR-20720",Chicago
2,74498,Maison Marais 1,391462,Georgia,NaN,st. roch,29.96986,-90.05172,entire home/apt,85.0,3,662,2025-06-29,3.75,3,231,28,23-XSTR-13082,Chicago
4,79609,Bywater's Original & Finest,428909,Stephen,NaN,st. claude,29.96448,-90.03667,entire home/apt,84.0,30,505,2025-03-05,2.86,1,291,3,"23-ISTR-02823, 23-OSTR-02823",Chicago
5,80869,"Frenchmen House ""Red Room""",437783,Joanne,NaN,marigny,29.96811,-90.05905,private room,80.0,1,996,2025-08-09,5.65,2,165,52,24-XSTR-08500,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7439,1505790522200679365,Elegant 3BR/3BA Condo • Near French Quarter,664618805,Leigh Ann Wilgus,NaN,central business district,29.94866,-90.07412,entire home/apt,135.0,1,0,NaT,0.00,31,347,0,23-xstr-21437,Chicago
7440,1505911712150280478,NOLA Swamp Retreat,326149155,Allen,NaN,new aurora - english turn,29.91035,-89.93537,entire home/apt,285.0,30,0,NaT,0.00,1,325,0,NaN,Chicago
7441,1505920980213506394,"Comfortable and Safe in NOLA, City Life Rural ...",25897556,Leslie,NaN,old aurora,29.92504,-89.99269,entire home/apt,90.0,30,0,NaT,0.00,1,365,0,NaN,Chicago
7442,1506561558220305779,Stylish Combo Unit: 3 Ensuites - Near FQ,664618805,Leigh Ann Wilgus,NaN,central business district,29.94857,-90.07458,entire home/apt,129.0,1,0,NaT,0.00,31,356,0,23-XSTR-21437,Chicago
7443,1506565692749570334,Spacious Combo Unit : 2 Ensuites - Near FQ,664618805,Leigh Ann Wilgus,NaN,central business district,29.94644,-90.07317,entire home/apt,124.0,1,0,NaT,0.00,31,356,0,23-XSTR-21437,Chicago

In [30]:
# Fill missing values
df_new_orleans['reviews_per_month'] = df_new_orleans['reviews_per_month'].fillna(0)

In [31]:

# Drop important nulls
df_new_orleans = df_new_orleans.dropna(subset=['price', 'neighbourhood', 'room_type'])

In [32]:

df_new_orleans['price'] = df_new_orleans['price'].replace(r'[\$,]', '', regex=True)

In [33]:


# Convert date
df_new_orleans['last_review'] = pd.to_datetime(df_new_orleans['last_review'], errors='coerce')

In [34]:


# Remove duplicates
df_new_orleans = df_new_orleans.drop_duplicates()

In [35]:

# Fix text
df_new_orleans['neighbourhood'] = df_new_orleans['neighbourhood'].str.lower().str.strip()
df_new_orleans['room_type'] = df_new_orleans['room_type'].str.lower().str.strip()

In [36]:

# Remove outliers
df_new_orleans = df_new_orleans[df_new_orleans['price'] < 1000]
df_new_orleans = df_new_orleans[df_new_orleans['minimum_nights'] < 365]

In [37]:

# Add city column
df_new_orleans['city'] = 'New Orleans'

In [38]:
df_new_orleans

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city
0,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,hyde park,41.787900,-87.587800,private room,119.0,3,257,2025-08-07,1.97,1,348,10,R17000015609,New Orleans
1,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,NaN,west town,41.901660,-87.680210,entire home/apt,89.0,2,595,2025-09-01,3.01,1,302,47,R24000114046,New Orleans
2,10945,The Biddle House (#1),33004,At Home Inn,NaN,lincoln park,41.911960,-87.639810,entire home/apt,203.0,4,129,2025-09-06,0.93,6,325,24,2209984,New Orleans
3,12140,Lincoln Park Guest House,46734,Shar And Robert,NaN,lincoln park,41.923570,-87.649470,private room,339.0,2,19,2025-09-07,0.15,1,156,3,2398451,New Orleans
4,28749,Quirky Bucktown Loft w/ Parking No Parties,27506,Lauri,NaN,logan square,41.920226,-87.679613,entire home/apt,258.0,2,265,2025-09-01,1.47,1,74,37,R24000113825,New Orleans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8658,1513821766801636584,"Urban Oasis - Walk to Restaurants, Transit & M...",481170999,Jorge,NaN,lake view,41.932920,-87.646100,entire home/apt,900.0,32,0,NaT,0.00,15,275,0,NaN,New Orleans
8659,1514427498735918146,Home Sweet Home,134092189,Michael,NaN,greater grand crossing,41.767300,-87.611890,entire home/apt,99.0,32,0,NaT,0.00,2,365,0,NaN,New Orleans
8660,1514602729230425948,Large Group Getaway|Two Units Chicago Bronzeville,475704779,Joseph,NaN,grand boulevard,41.822410,-87.621090,entire home/apt,559.0,1,0,NaT,0.00,6,365,0,R24000121494,New Orleans
8661,1514621681093690520,Group Friendly Combo Units 1 & 2 Chicago,475704779,Joseph,NaN,grand boulevard,41.821490,-87.620280,entire home/apt,559.0,1,0,NaT,0.00,6,365,0,R24000121494,New Orleans
8662,1514812314516488457,Full apartment in the Heart of Chicago,22524505,Samandra,NaN,lower west side,41.852070,-87.679180,entire home/apt,68.0,38,0,NaT,0.00,1,171,0,NaN,New Orleans

In [39]:
# combine both
df = pd.concat([df_chicago, df_new_orleans], ignore_index=True)

In [40]:
df.shape
df['city'].value_counts()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13746 entries, 0 to 13745
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              13746 non-null  int64
 1   name                            13746 non-null  str
 2   host_id                         13746 non-null  int64
 3   host_name                       13150 non-null  str
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   13746 non-null  str
 6   latitude                        13746 non-null  float64
 7   longitude                       13746 non-null  float64
 8   room_type                       13746 non-null  str
 9   price                           13746 non-null  float64
 10  minimum_nights                  13746 non-null  int64
 11  number_of_reviews               13746 non-null  int64
 12  last_review                     11414 non-null  datetime64[us]
 13  reviews_per_month               13746 non-null  float64
 14  calculated_host_listings_count  13746 non-null  int64
 15  availability_365                13746 non-null  int64
 16  number_of_reviews_ltm           13746 non-null  int64
 17  license                         10303 non-null  str
 18  city                            13746 non-null  str
dtypes: datetime64[us](1), float64(5), int64(7), str(6)
memory usage: 2.0 MB

In [41]:
# EDA Comparison
df['city'].value_counts()

city
New Orleans    7647
Chicago        6099
Name: count, dtype: int64

In [42]:
df.groupby('city')['price'].mean()

city
Chicago        176.159534
New Orleans    188.811822
Name: price, dtype: float64

In [51]:
import sys
!{sys.executable} -m pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
df.to_excel("final_airbnb_data.xlsx", index=False)

In [ ]:
# Insights